- assets/javascripts/discourse/initializers/header.js.es6
- assets/javascripts/discourse/initializers/topic.js.es6
- assets/stylesheets/_components--topic.scss
This PR fixes some issues in the post in both desktop and mobile view
**centering name with avatar**
**centering name with avatar on mobile and reducing margins**
> topic posts fixes

- assets/stylesheets/mobile/_components--category-list.scss
- assets/stylesheets/mobile/_components--topic-list.scss
- assets/stylesheets/mobile/main.scss
- plugin.rb
Closes https://github.com/debtcollective/parent/issues/249
_Fixes:_
- Topic-list aesthetic details on mobile devices
> Fix aesthetics related to topic-list on mobile devices

- common/common.scss
- mobile/mobile.scss
- scss/button.scss
- scss/discourse/button.scss
- scss/templates/topic.scss
- scss/variables.scss
- scss/widgets/select-kit.scss
**What:**
This is a new pull request copying a previous one https://github.com/debtcollective/discourse-debtcollective-theme/pull/24 **after merge accidentally against a branch different from development**
> Topic footer buttons

- common/common.scss
- javascripts/discourse/initializers/dc-post.js.es6
- javascripts/discourse/initializers/dc-topic-timeline.js.es6
- javascripts/discourse/templates/topic.hbs
- scss/widgets/topic-timeline.scss
**What:**
Add customisation for the sidebar control (topic timeline) within topic detail view
**Why:**
Last activity to Close https://github.com/debtcollective/community/issues/30
**How:**
- Add SCSS to customise buttons on topic-timeline and also change the layout distribution of the widget in order to meet design requirements. a0e06fa
- Render topic-progress for everything less than 1200px acd59ee
**Extra:**
- Fix issue with topic detail rendering empty due to TypeError ec72ecf
**Media:**
https://www.loom.com/share/5f5ba515f0ef40f19a427b7c414ee316
> Topic navigation

- javascripts/discourse/templates/list/dc-topic-card.hbr
- javascripts/discourse/widgets/dc-topic-title.js.es6
- scss/widgets/post.scss
**What:**
Fix issue render topic titles
**Why:**
re https://app.asana.com/0/1156905606552066/1164263463757819
**How:**
- Escape text accordingly for hbs and widgets approaches
**Media:**
> Fix title render issues

- common/common.scss
- javascripts/discourse/templates/components/categories-only.hbs
- javascripts/discourse/templates/components/dc-categories-only.hbs
- javascripts/discourse/templates/components/dc-category-card.hbs
- javascripts/discourse/templates/mobile/components/categories-only.hbs
- locales/en.yml
- scss/layout.scss
- scss/templates/components/list-controls.scss
**What:**
After perform a preview of the theme within production this PR bundles a couple minor aesthetic updates for the community.
**Why:**
No issues related, just manual QA and update of the code.
> Add latest aesthetic updates related navigation and layout

- common/common.scss
- javascripts/discourse/templates/components/dc-topic-list-item-small.hbs
- javascripts/discourse/templates/topic.hbs
- scss/templates/composer.scss
**What:**
Add improvements to support event plugin
**Why:**
Closes https://app.asana.com/0/1168997577035609/1164263463757819
**How:**
- Add the topic-title-outlet into the topic markup 920ab86
**Extras:**
- Avoid issue rendering topic title with `'` a6d829d
- Improve composer aesthetics c58d227
**Media:**
https://www.loom.com/share/0d06d3feb9ba497498b35583af93d1e3
> Add event support and minor aesthetics improvements

- javascripts/discourse/templates/components/dc-hero.hbs
- locales/en.yml
**What:**
Deprecate one link on the hero and add link value
**Why:**
Closes https://app.asana.com/0/1168997577035609/1169895868852861
_(last activity to activate the hero)_
> fix(hero): remove one CTA item and add customisable link

- javascripts/discourse/components/categories-only.js.es6
- javascripts/discourse/components/dc-category-card.js.es6
- javascripts/discourse/templates/components/dc-category-card.hbs
**What:**
Copy of PR https://github.com/debtcollective/discourse-debtcollective-theme/pull/48
**Why:**
The PR #48 wasn't merged to the `development` branch.
> Category members count

- scss/templates/components/d-navigation.scss
- scss/templates/topic.scss
- scss/widgets/post.scss
- scss/widgets/topic-timeline.scss
**What:**
Improve alignment over items within the topic detail view.
1. Align icons on float button
2. Better align for post information
**Why:**
re https://app.asana.com/0/1168997577035609/1177325089116025
**Media:**
https://www.loom.com/share/f1faf45e72c34246b11620e94a394b00
> Topic detail page improvements

- javascripts/discourse/components/dc-categories-nav.js.es6
- scss/connectors/categories-nav.scss
**What:**
Add better responsiveness for category navigation
**Why:**
re https://app.asana.com/0/1168997577035609/1169241432207403
**How:**
1. Add an event for user scroll hide the navigation (which play nicely with Discourse header animation)
2. Reduce the font size on mobile devices
_PD: I sorted CSS properties so there is a bit of noise there..._
**Media:**
https://recordit.co/6yIIQ2cUuf
> Categories navigation improvement

- javascripts/discourse/components/dc-categories-only.js.es6
- javascripts/discourse/templates/components/dc-categories-only.hbs
- mobile/mobile.scss
- scss/templates/components/d-navigation.scss
- scss/templates/components/list-controls.scss
**What:**
Allow users to create categories from the homepage
**Why:**
closes https://app.asana.com/0/1168997577035609/1175878972689347
**How:**
- Use the method and component regarding category creation on `d-navigation` from Discourse within our custom categories component
**Media:**
> Add actions to create content on homepage

- common/common.scss
- javascripts/discourse/initializers/dc-login-controller.js
- javascripts/discourse/initializers/dc-modal-body.js
- javascripts/discourse/initializers/dc-modal.js
- javascripts/discourse/templates/components/d-modal.hbs
- javascripts/discourse/templates/mobile/modal/create-account.hbs
- javascripts/discourse/templates/mobile/modal/login.hbs
- javascripts/discourse/templates/modal/create-account.hbs
- javascripts/discourse/templates/modal/forgot-password.hbs
- javascripts/discourse/templates/modal/login.hbs
- mobile/mobile.scss
- package.json
- scss/button.scss
- scss/card.scss
- scss/forms.scss
- scss/login.scss
- scss/variables.scss
**What:** New designs for login, signup and other related screens
**Email/Password**
https://www.loom.com/share/25963498cdb64b18a16dccf871c93b09
**Social Auth**
https://www.loom.com/share/33542a8acd614fa69bc145ec68a30541
**Why:** Related to https://app.asana.com/0/1159164196409226/1164578890975612.
**How:**
- Customize modals to make them look like designs
- Customize modal to behave like a full screen view.
> New designs for login, signup and other related screens

- javascripts/discourse/initializers/dc-modal.js
- javascripts/discourse/templates/components/d-modal.hbs
- javascripts/discourse/templates/modal/create-account.hbs
- javascripts/discourse/templates/modal/forgot-password.hbs
- javascripts/discourse/templates/modal/login.hbs
- mobile/mobile.scss
- scss/button.scss
- scss/connectors/hero.scss
- scss/forms.scss
- scss/layout.scss
- scss/login.scss
**What:**
Fix layout for the login modal
**Why:**
re https://app.asana.com/0/1168997577035609/1179368978953596
**How:**
In regards scroll position:
1. Use CSS in order to do all that is possible to preserve scroll position
2. Add enhanced experience with JS to save scroll position
In regards layout:
_Just CSS with <3_
**Extras:**
- Update some sizes, styles, spaces and overall aesthetics
**Media**
1. [Login and Signup form none native showcase](https://www.loom.com/share/892c7e49794242c4b5b28b4a64b2dd20)
1. [Browserstack showcase](https://www.loom.com/share/55cd9bba1e41413eae4bde9b74224dca)
> Login modal fixes

- javascripts/discourse/templates/components/dc-menu.hbs
- scss/connectors/dc-menu.scss
**What:**
Enable to click on any part of the card to behave like a link
**Why:**
Currently, the anchor tag is just the text which makes the whole card not do anything unless you click the text.
**How:**
I turn the card into an anchor and put the text content into a span tag
Asana ticket: https://app.asana.com/0/1159164196409156/1183391677913101/f
Media: https://www.loom.com/share/0696a6c4cb9944e08fb01238b26087df
> feat(dc-menu): fix menu items, enable to click anywhere on the menu card

- LICENSE
- common/common.scss
- javascripts/discourse/components/dc-collective-alert.js.es6
- javascripts/discourse/connectors/discovery-list-container-top/collective-alert.hbs
- javascripts/discourse/connectors/topic-above-post-stream/collective-alert.hbs
- javascripts/discourse/initializers/dc-collectives-alert.js.es6
- javascripts/discourse/templates/components/dc-collective-alert.hbs
- javascripts/discourse/templates/components/topic-footer-buttons.hbs
- javascripts/discourse/widgets/post-menu.js.es6
- mobile/mobile.scss
- package.json
- scss/variables.scss
- scss/widgets/dc-collectives-alert.scss
**What:** merge discourse-debtcollective-collectives plugin
**Why:** Closes https://app.asana.com/0/1168997577035609/1179368978953609
**How:**
- Merge front-end code from https://github.com/debtcollective/discourse-debtcollective-collectives.
- Fix issue with lint-staged not processing files with ext `.js.es6` or `.es6`
- Add LICENSE file
> feat: merge discourse-debtcollective-collectives plugin

- javascripts/discourse/widgets/dc-topic-title.js.es6
- scss/widgets/post.scss
**What:**
Add tags on topics
**Why:**
To address: https://app.asana.com/0/1159164196409129/1186091925043867/f
**How:**
- Add category on a topic title
- Add tags on a topic title
**Media**
> feature(topics): add topic tags

- scss/templates/user.scss
**What:**
Improve user stats styles
**Why:**
To address: https://app.asana.com/0/1159164196409129/1186341795801831/f
**How:**
Applying styles from the [design](https://www.figma.com/file/Tgjsq8aFgxMeOjOc3E9ybS/community-mockups?node-id=0%3A381)
Media:
> feat(user-profile): improve user stats design

- javascripts/discourse/initializers/dc-login-controller.js
- javascripts/discourse/initializers/dc-user-controller.js
- javascripts/discourse/widgets/dc-topic-title.js.es6
- scss/templates/user.scss
**What:**
Update user profile header to match with the design
**Why:**
To address: https://app.asana.com/0/1159164196409129/1186341795801831/f
**How:**
- Display user profile always expanded
- Hide button to collapse/expand profile
- Update styles on a user profile header
Media:
- [Admin](https://recordit.co/i2pTjw2BEB)
- [Normal user](https://recordit.co/BBTEiJzYTh)
> feat(user-profile): improve user profile header to match with design

- javascripts/discourse/components/dc-collective-alert.js.es6
- javascripts/discourse/templates/components/dc-collective-alert.hbs
- locales/en.yml
- scss/variables.scss
- scss/widgets/dc-collectives-alert.scss
**What:**
Update debt collective alert styles
**Why:**
To address: https://app.asana.com/0/1159164196409129/1186341795801831/f
**How:**
- Change the position of button and label
- Update colors to match the design
- Add join icon to theme assets
https://www.loom.com/share/2880b22b485044d0aca1a03a112a286e
> feat(dc-collective-alert): update styles to match design

- scss/templates/user.scss
**What:**
Update design from user badges section
**Why:**
To address: https://app.asana.com/0/1159164196409129/1186341795801831/f subtask 8
**How:**
- By overwriting style rules to match with new design
Media:
> Update design from user badges section

- scss/button.scss
- scss/discourse/button.scss
- scss/templates/user.scss
- scss/widgets/dc-collectives-alert.scss
**What:**
Update aesthetics issues with the community components after admin UI update
**Why:**
To address: https://app.asana.com/0/1168997577035609/1188757815548472/f
**How:**
- Changing menu colors to the primary color
- Unify buttons design
- Use flex display to fix user header layout
- Use fluid units to define spaces
- Remove icons from vertical menus
Media:
https://www.loom.com/share/44f39505b5b54ae8ab8ca095d5c66e90
> fix(user-profile): apply style fixes to user profile

- javascripts/discourse/initializers/dc-header.js.es6
- javascripts/discourse/templates/components/dc-menu.hbs
- locales/en.yml
- scss/connectors/dc-menu.scss
- scss/variables.scss
- scss/widgets/header.scss
**What:**
- Set the same design as the header being used across our different applications
**Why:**
- Relates to: https://app.asana.com/0/1196225495304457/1196365498597563/f
**How:**
- Add the new links to the header and the dc-menu
- Update the header and the dc-menu styles
- Update the buttons for the header, now we have `Member Login` and `Donate`
https://www.loom.com/share/8f794e4dca4e495a961e16447a479c49
> Header updates

- javascripts/discourse/templates/modal/login.hbs
**What:** show join the union link on login modal
**Why:** Fixes https://app.asana.com/0/1196225495304457/1198222899212557 and Related to https://app.asana.com/0/1196225495304457/1196439491713547
**How:**
> dev(disable-signup): show join the union link on login modal

- javascripts/discourse/initializers/dc-header.js.es6
- javascripts/discourse/templates/components/dc-menu.hbs
- scss/connectors/dc-menu.scss
- scss/variables.scss
**What:**
Include take action links
**Why:**
Closes: https://app.asana.com/0/1196225495304457/1196365498597563/f
**How:**
Use the details/summary tags to include the links
https://www.loom.com/share/26efa988f9474688ab230e130460276c
> Include take action links

- javascripts/discourse/initializers/dc-post.js.es6
- scss/widgets/post.scss
Reverts debtcollective/discourse-debtcollective-theme#110
There's an issue I need to fix before merging this
> Revert "feat: enable topic-map in private messages"

- javascripts/discourse/initializers/dc-post.js.es6
- scss/widgets/post.scss
**What:** enable topic-map in private messages
**Why:** fixes https://app.asana.com/0/1168997577035609/1182505564098417
**How:**
- enable topic-map on the first private message.
**Media:**
**Notes:**
I had to a revert https://github.com/debtcollective/discourse-debtcollective-theme/pull/112, the issue is fixed on this PR
> feat: enable topic-map in private messages

- javascripts/discourse/templates/components/d-navigation.hbs
- javascripts/discourse/templates/components/dc-sidebar.hbs
- javascripts/discourse/templates/navigation/category.hbs
- scss/templates/components/list-controls.scss
- scss/templates/navigation/category.scss
- scss/widgets/post.scss
**What:**
Add button to create topic on top of the sidebar
**Why:**
https://app.asana.com/0/1168997577035609/1199979488935302
**How:**
Hide previous one that where within the category navigation to create topics
**Media:**
https://www.loom.com/share/48a00fcb8d0647fea3b97a515e440937
> Sidebar top button (new topic)

- .hintrc
- package.json
- yarn.lock
**What:**
Setup hint and add not dead browsers to browserlist
**Why:**
Relates to: https://app.asana.com/0/1168997577035609/1199915290849534/f
**How:**
Install hint dependency and web recommended hint config
> Setup hint and add not dead browsers to browserlist
