debtcollective/discourse-debtcollective-theme

assets/stylesheets/_components--modal.scss, assets/stylesheets/_components--signup-form.scss, assets/stylesheets/main.scss
fixes user fields rendering one of top of the other.
Closes debtcollective/community#6
**iPhone 6s**
**Galaxy S9**
=> fix(Signup): using min-height instead of max-height

assets/javascripts/discourse/initializers/html-classes.js.es6, assets/javascripts/helpers/device.js.es6, assets/stylesheets/_components--modal.scss, assets/stylesheets/_layouts--body.scss, plugin.rb
**What:** Add fixes for signup modal and double scroll issue when modal is open
**Why:** Closes https://github.com/debtcollective/dispute-tools/issues/186
**How:**
What we need to understand is that iOS Safari doesn't support the `overflow: hidden` method to avoid double scroll when a modal is being shown. In that sense to fix the double scroll issue this code adds:
- A way to detect the browser using JS
- Add a extra class to map with CSS and add the fix whenever is needed
- Skip iOS >= 13 and desktop browsers as they doesn't need the fix
Further info about it can be found at: https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/
Besides, in order to avoid the cropped modal we need to:
- Overwrite css style from core team that always force the scrollbar
- Use % instead vh …
=> Fix: signup fields and modal issues

assets/stylesheets/_components--modal.scss
**What:** let modal scroll lazy
**Why:** to improve modal scrolling on mobile devices
**How:** adding `-webkit-overflow-scrolling: touch;` to inner modal
https://www.loom.com/share/86580db4a82e45fab6a0538e6fbfcaa9
=> dev: let modal scroll lazy

common/common.scss, javascripts/discourse/templates/components/dc-categories-only.hbs, javascripts/discourse/templates/components/dc-category-card.hbs, package.json, scss/card.scss, scss/functions.scss, scss/layout.scss, yarn.lock
**What:** Add categories topic count
**Why:** 
re https://github.com/debtcollective/community/issues/28
**How:** 
Use category model method that is already used by default discourse theme
**Bonus:**
- Create a single file to render the category card
- Add new font weight of 300 to follow designs
- Improve layout and aesthetics of card to follow design
**Screenshots:**
=> Add categories topic count

common/common.scss, javascripts/discourse/initializers/dc-topic-list.js.es6, javascripts/discourse/templates/components/dc-category-card.hbs, javascripts/discourse/templates/components/topic-list.hbs, javascripts/discourse/templates/list/topic-author.raw.hbs, javascripts/discourse/templates/list/topic-list-item.raw.hbs, scss/card.scss, scss/pill.scss, scss/templates/components/categories-only.scss, scss/templates/components/topic-list.scss, scss/templates/list/topic-author.scss, scss/type.scss, scss/variables.scss
**What:** Add initial customisation for the category topic list page
**Why:** 
re https://github.com/debtcollective/community/issues/29
**How:**
- Replace topic-list template 
- Avoid to render table based grid on topic-list and topic-list-item components
**Extras:**
- Unify height of cards on categories and topic list item
- Improve overall card component to be easier to use within different contexts
**Screenshots:**
=> Category topic list page

javascripts/discourse/templates/list/topic-list-item.raw.hbs, scss/card.scss
**What:** Fixes for the customisation of topic list item
**Why:** re https://github.com/debtcollective/community/issues/29
**How:**
- Avoid to render the whole default raw template which cause broken layout check a2f3d0b
- Avoid icons to change colour as link text on hover e219658
**Screenshots:**
=> Fix topic list item

.gitignore, .vscode/settings.json, common/common.scss, javascripts/discourse/components/dc-show-more.js.es6, javascripts/discourse/helpers/dc-format-date.js.es6, javascripts/discourse/templates/components/dc-show-more.hbs, javascripts/discourse/templates/components/topic-list.hbs, javascripts/discourse/templates/list/dc-topic-card.hbr, locales/en.yml, scss/button.scss, scss/card.scss, scss/discourse/button.scss, scss/layout.scss, scss/templates/components/dc-show-more.scss, scss/type.scss, scss/variables.scss
**What:** 
Add show more functionality
**Why:** 
Closes https://github.com/debtcollective/community/issues/29
**How:**
- https://github.com/debtcollective/discourse-debtcollective-theme/commit/726f3e5fc6e1f6d1f094eb1d4766d9714df0d791 create a component to handle the feature
- https://github.com/debtcollective/discourse-debtcollective-theme/commit/4b01e714bf2d965f86a599cd55729133e4f22c60 include the component on the topic-list
**Media:**
**Extras:**
- Update VSCode to not use ts check
- Remove "last visited" text from being floating alongside the topics 7f06bd6
- Use real date instead hard coded one f5e9a74  9c64c55
- Fix usage of colours and variables to better adopt Bootstrap patterns 91c5cb4 50ce80a
=> Add "show more" on topic list

common/common.scss, javascripts/discourse/initializers/dc-post.js.es6, javascripts/discourse/templates/components/topic-category.hbs, javascripts/discourse/templates/topic.hbs, javascripts/discourse/widgets/dc-topic-title.js.es6, scss/layout.scss, scss/templates/topic.scss, scss/type.scss, scss/variables.scss, scss/widgets/post.scss
**What:**
Add initial customisation of topic page by adding:
- Breadcrumps
- Base to adopt cards as containers for post
**Why:**
re https://github.com/debtcollective/community/issues/30
**Media:**
**How:**
For the nature of the code on topic page we need to reopen several widgets related to the topic posts, to have a basic understanding of the hierarchy is important to mention that `topic.hbs` works like: 
```
"templates/topic.hbs"
"components/scrolling-post-stream.js.es6"
"widgets/post-stream.js.es6"
"widgets/post.js.es6" -> several widgets for post composition
```
**Extras:**
- Change all links to follow the same color as design _"red"_
- Change body background to be the gradient one in the design
=> Base to customise topic detail view

common/common.scss, javascripts/discourse/initializers/dc-post.js.es6, scss/button.scss, scss/templates/topic.scss, scss/variables.scss, scss/widgets/embedded-posts.scss, scss/widgets/post-controls.scss, scss/widgets/post.scss
**What:**
Add support for embedded posts (replies) and adjust markup of post actions to render as design suggest.
**Why:**
re https://github.com/debtcollective/community/issues/30
**How:**
- reopen widgets related to post such as: `post-avatar` `post-body` `post-article` `post-contents` `post-meta-data` aiming to preserve a lot of the built-in code by discourse but also introducing the usage of grid system we handle.
**Media:**
[Extended UI can be check here](https://user-images.githubusercontent.com/1425162/74967034-81b08900-5418-11ea-8031-773f1665ee4a.png)
**Note:** _styles on mobile may need to be yet adjusted a little bit to perhaps show avatars of posters and update few spaces (in another PR)_
=> Topic detail card actions

common/common.scss, javascripts/discourse/components/dc-show-more.js.es6, javascripts/discourse/templates/components/dc-topic-list-item-small.hbs, javascripts/discourse/templates/components/suggested-topics.hbs, javascripts/discourse/templates/components/topic-list.hbs, javascripts/discourse/templates/list/dc-topic-card.hbr, javascripts/discourse/templates/topic.hbs, scss/card.scss, scss/functions.scss, scss/layout.scss, scss/pill.scss, scss/templates/components/topic-list.scss, scss/templates/list/dc-topic-author.scss, scss/templates/list/dc-topic-card.scss, scss/utils.scss, scss/variables.scss, scss/widgets/embedded-posts.scss
**What:**
Add customisation for suggested topic list
**Why:**
re https://github.com/debtcollective/community/issues/30
**How:**
Replace the https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/templates/components/suggested-topics.hbs template
**Extras:**
- Improve "show-more" component to avoid hide all content when no pinned topics c1c2003
- Refactor of topic-card to use grid system 80e0942
**Media:**
=> Suggested topic list

common/common.scss, mobile/mobile.scss, scss/button.scss, scss/discourse/button.scss, scss/templates/topic.scss, scss/variables.scss, scss/widgets/select-kit.scss
**What:**
Add basic customisation to follow design over topic footer buttons
**Why:**
re https://github.com/debtcollective/community/issues/30
**How:**
- Add CSS updates over the buttons on topic footer buttons
**Extras:**
- Add missing space for post-menu on mobile devices
- Avoid transition `all` on buttons
- Incorporate `select-kit` basic customisation for coherent UI
**Media:**
[Mobile screenshot](https://user-images.githubusercontent.com/1425162/75347632-725e8f00-58a1-11ea-8f53-5c200dd8cc0a.png)
=> Topic footer buttons

scss/templates/topic.scss
**What:**
- Allow all dividers to set width 100%
- Add margin top to time gaps dividers
**Why:**
re https://app.asana.com/0/1160587988086971/1164497105920009
**Media:**
=> fix(topic): dividers full width and time gaps with top margin

common/common.scss, javascripts/discourse/initializers/dc-header.js.es6, javascripts/discourse/templates/components/topic-list-item.hbs, javascripts/discourse/templates/list/dc-topic-card.hbr, javascripts/discourse/templates/list/topic-list-item.hbr, locales/en.yml, mobile/mobile.scss, scss/templates/list/dc-topic-card.scss, scss/templates/user.scss, scss/widgets/header.scss, scss/widgets/user-menu.scss
**What:**
Add base for header customisation and button with notifications
**Why:**
re https://github.com/debtcollective/community/issues/27
**How:**
- Reopen several widgets involved within the header creation and SCSS customisation so we hide the icons and show them within the header with their badges of counts.
**Extras:**
- Fix the topic list item to have support for bulk selection _(check video sec 34)_ efa1a4d
**Media:**
https://www.loom.com/share/dca06bcd7c4949ed8886ebbd0bd6f96a
=> Add base for custom header

scss/widgets/header.scss
**What:**
Make sure header buttons render before user-menu
**Why:**
After seeing the theme preview we spot some differences
**Media:**
**Before:**
**After:**
=> fix(header): move header-buttons to always render first than user-menu

scss/templates/components/list-controls.scss
**What:**
Set display none for list-controls within the homepage
**Why:**
Closes https://app.asana.com/0/1159164196409129/1167976328111755/f
**How:**
- Keep a similar approach to #33 that renders the hero only in homepage _(we do the same but to remove only on the homepage)_
=> Remove the navigation component from homepage

common/common.scss, javascripts/discourse/templates/components/topic-list.hbs, javascripts/discourse/templates/list/visited-line.hbr, scss/templates/list/visited-line.scss, scss/widgets/header.scss
**What:**
Add a line to separate the topics that have any updates from last visited
**Why:**
Closes https://app.asana.com/0/1159164196409156/1168068725630293
**How:**
Use Discourse built-in approach with custom template
**Media:**
=> Add "latest activity" support

javascripts/discourse/templates/components/dc-category-card.hbs, javascripts/discourse/templates/list/dc-topic-card.hbr
**What:**
Add clamp utility within titles for categories and topics
**Why:**
Closes https://app.asana.com/0/1159164196409156/1168068725630295
**How:**
Use our utility class `dc-clamp-N`
**Media:**
- [How it looks before](https://app.asana.com/0/1159164196409156/1168068725630295)
- [How it looks now](https://user-images.githubusercontent.com/1425162/77678636-bcff2400-6f91-11ea-90e4-0f4e67c0153e.png)
=> Fix titles to have a limit of lines to avoid broken layout

javascripts/discourse/initializers/dc-header.js.es6, scss/widgets/header.scss
**What:**
Update header-buttons order when user has logged that in order to avoid:
**Why:**
We use to fix it https://github.com/debtcollective/discourse-debtcollective-theme/pull/31 and it come up again now in logged cases
**How:**
Add aux class to make difference on header when user logged and when it is not
=> Add header aux class to detect logged user and update items

javascripts/discourse/initializers/dc-header.js.es6
**What:**
After rush the solution at https://github.com/debtcollective/discourse-debtcollective-theme/pull/37 I miss a `.` within class selector
**Why:**
We need the selector to be right to properly add the class
**How:**
Add the `.` to the selector
=> fix(header): typo on class selector

javascripts/discourse/templates/components/dc-category-card.hbs, javascripts/discourse/templates/list/dc-topic-card.hbr, scss/templates/list/dc-topic-card.scss, scss/variables.scss
**What:**
Decrease the height of the categories/topic cards while keeping the aspect ratio from topic card small version.
**Why:**
Closes https://app.asana.com/0/1168997577035609/1169090498305145
**How:**
- Update global variables
- Detach small topic card from variables
**Media:**
- [How topics looks like](http://g.recordit.co/lXVZX3a7cS.gif)
- [How topic small looks like](https://user-images.githubusercontent.com/1425162/77998588-9d6d5000-7331-11ea-8039-f8145f67b024.png)
=> Adjust card height

javascripts/discourse/components/dc-show-more.js.es6, javascripts/discourse/templates/components/dc-show-more.hbs
**What:**
Hide the loading container until component gets expanded
**Why:**
Closes https://app.asana.com/0/1168997577035609/board
The idea is to avoid to show a "show more" button with a text that already said "there is nothing more" or perhaps the loading spinner.
**How:**
- Add a "loadingContainerSelectors" within a new method "_hideLoadingMessage" that will address the problem within the topic list _(only place we currently use the show more component)_
- Small refactor to enclose intended actions on lifecycle within a method
**Media:**
=> Integrate "show more" with loading flow

javascripts/discourse/components/categories-only.js.es6, javascripts/discourse/templates/components/categories-and-latest-topics.hbs, javascripts/discourse/templates/components/categories-only.hbs, javascripts/discourse/templates/components/dc-categories-only.hbs, javascripts/discourse/templates/mobile/components/categories-only.hbs, locales/en.yml, scss/templates/list/dc-topic-card.scss, settings.yml
**What:**
Add a section that allows to render pinned topics in form of "current efforts"
**Why:**
Closes https://app.asana.com/0/1168997577035609/1168068725630291
**How:**
We inject the current topic data we have on the homepage into the `category-only` template and then filter pinned topics within `currentEfforts`.
**Extras:**
- Optimise the `categories-only` template to not need double iteration over categories. 6dc74b1
- Remove fixed height for `topic-small` 88b5b2b
🚨**Important:**
The homepage only have access to the ["latest topics" check discourse core code](https://github.com/discourse/discourse/blob/38dd184a16f38fed1f011eeb39de580a301b8f4e/app/assets/javascripts/discourse/routes/discovery-categories.js.es6#L48) so we need to deliver to the client the pinned topics so we can render …
=> Current efforts within homepage

javascripts/discourse/components/categories-only.js.es6, javascripts/discourse/templates/components/dc-categories-only.hbs, javascripts/discourse/templates/mobile/components/categories-only.hbs
**What:**
Add default value to return by topics on currentEfforts
**Why:**
`currentEfforts` computation needs `topics` but for some reason this can be `undefined` (need to dig more into it) but currently the community is broken due to this.
**How:**
- Attempt to flag the feature up so the code doesn't get triggered
- Add fallback to empty array 8287f38
=> Avoid fatal error for empty topics

javascripts/discourse/initializers/dc-homepage.js.es6, javascripts/discourse/templates/components/categories-and-latest-topics.hbs
**What:**
Enable global pinned topics by forcing to load latest topics within homepage
**Why:**
We need access to the latest topics to render globally pinned topics
**How:**
Update the route `discovery-categories` to always use the `this._findCategoriesAndTopics("latest")` strategy which is used to load latest topics.
**Screenshots**
_Note: you can tested with [live community here](https://community.debtcollective.org/?preview_theme_id=15)_
=> Global pinned topics

about.json
**What:**
Render topic excerpt on topic list cards
**Why:**
re https://app.asana.com/0/1168997577035609/1169229929310113
**How:**
After research and [open a topic on the community](https://meta.discourse.org/t/how-to-add-topic-excerpt-to-all-my-topics/148903) we found the solution
**Media:**
=> feat(about): allow theme to force excerpt on topics

javascripts/discourse/components/categories-only.js.es6, javascripts/discourse/components/dc-category-card.js.es6, javascripts/discourse/templates/components/dc-category-card.hbs
**What:**
Allow to render members count
**Why:**
re https://app.asana.com/0/1168997577035609/1166394121215209
**How:**
- Create a new component that expose `groupCount` into category card
**Media:**
[Categories that are not collectives doesn't have members count](https://user-images.githubusercontent.com/1425162/80246498-ce108300-866c-11ea-8069-c922086f3904.png)
**Notes:**
This PR needs https://github.com/debtcollective/discourse-debtcollective-collectives/pull/3 to work as expected on production
=> Category members count

javascripts/discourse/initializers/dc-home-logo.js.es6, settings.yml
**What:**
Allow to change the logo href without code
**Why:**
This is a change that product as asked for, as from a tech perspective
seems to not be a good decision we enable the flexibility to easily tweak it
re https://app.asana.com/0/1168997577035609/1172273375528964
**How:**
Define a setting from the theme that take effect on the home-logo widget.
=> feat(home-logo): allow to set home logo href using settings

common/common.scss, javascripts/discourse/components/dc-show-more.js.es6, javascripts/discourse/initializers/dc-navigation.js.es6, javascripts/discourse/templates/components/d-navigation.hbs, javascripts/discourse/templates/discovery.hbs, javascripts/discourse/templates/navigation/default.hbs, mobile/mobile.scss, scss/templates/components/d-navigation.scss, scss/templates/components/list-controls.scss, scss/templates/components/navigation-bar.scss, scss/variables.scss, scss/widgets/select-kit.scss
**What:**
Improve the customization of the navigation item
**Why:**
It used to feel off from the theme and also some details make it confusing.
re https://app.asana.com/0/1168997577035609/board
**How:**
- Customise the navigation component
- Add title and description of the category as a more explicit content on the page
- Remove link to go to categories when latest so we avoid confusion with global latest and home
- Prevent show more to take place on latest page
**Media**
- [Loom video](https://www.loom.com/share/8e356da2b94d4442909a3258da491caa)
- [Mobile screenshot](https://user-images.githubusercontent.com/1425162/81974051-4d1e2900-9625-11ea-8ee8-9faaa8568102.png)
=> Category page navigation improvements

javascripts/discourse/templates/topic.hbs
**We need to sync the deployment of this, first Discourse needs to be updated before we can update the theme on production**
**What:** rename toggleBookmarkWithReminder to toggleBookmark
following the change on Discourse https://github.com/discourse/discourse/pull/9579
**Why:** To make the theme work with the latest Discourse version
**How:**
- rename toggleBookmarkWithReminder to toggleBookmark
=> fix: rename toggleBookmarkWithReminder to toggleBookmark

javascripts/discourse/templates/components/d-navigation.hbs, scss/templates/components/d-navigation.scss, scss/templates/components/navigation-bar.scss
**What:**
Make sure description support rich text
**Why:**
The description of a category is being done with a topic "About topic", the content of this is a rich text and we should show it as such. (Allowing to use links, bold, italic... etc)
**How:**
- Use hbs built-in solution `{{{value}}}`
- Add remote URL for d-navigation component
**Media**
[Before the description was displayed as shown here](https://user-images.githubusercontent.com/1425162/82149684-6f978880-9857-11ea-980c-83263ff9b7f8.png)
=> Fixes category page

javascripts/discourse/initializers/dc-popup.js.es6, locales/en.yml, settings.yml
**What:**
Render popup component within the community
**Why:**
https://app.asana.com/0/1168997577035609/1175421826877181
**How:**
Set a script on `page:changed` event from Discourse to load the popup distribution and append the component.
**Note:** we have a flag that prevent to be doing this on every change but there is no other event from discourse that more or less fit our need.
**Media:**
https://www.loom.com/share/2b066bccf2184c248241100e8ec4f643
=> Add popup to the community page

javascripts/discourse/initializers/dc-post.js.es6, javascripts/discourse/templates/components/dc-categories-only.hbs, scss/widgets/post.scss
**What:**
Allow avatar flair to be visible
**Why:**
We need the distinction of staff users. 
**How:**
- While the component was being rendered properly Discourse expect it to be within certain conditions (a parent relative and with the class `.user-image`) to render properly
**Media:**
=> Avatar flair to render properly

common/common.scss, javascripts/discourse/templates/components/dc-category-card.hbs, scss/layout.scss, scss/templates/components/cta-signup.scss, scss/widgets/post.scss
**What:**
Address some known/unknown visual issues on the community
**Why:**
- Closes https://app.asana.com/0/1168997577035609/1177393609854433 fa389b9
- Closes https://app.asana.com/0/1168997577035609/1177708595506649 f6ff410
**Extras:**
We are fixing also:
- White icon on reply for mobile 1ce1248
- `signup-cta` to be as wider as the post stream 3f3b4b6
- Background of the site to always fill the entire page 807bc5a
**Media:**
https://cln.sh/QDN5x6 , https://cln.sh/GnvYTd , https://cln.sh/jsxMdj
=> Aesthetics improvements

javascripts/discourse/components/categories-only.js.es6
**What:**  use `Topic.pinned_globally` instead of `Topic.pinned` to display current efforts
**Why:** Fixes https://app.asana.com/0/1168997577035609/1178339208108259
`Topic.pinned` is based on user preferences, while `Topic.pinned_globally` is always returns `true` until the topic is unpinned.
**How:**
- Change topic filter from `pinned` to `pinned_globally`
=> feat(current-efforts): use pinned_globally instead of pinned

common/common.scss, scss/templates/preferences.scss
**What:**
Prevent users to have access to the homepage control
**Why:**
We want to force all users to have the same homepage
**How:**
Hide the control using CSS and then we will run a script to set the homepage id
**Media:**
=> feat(preferences): hide control of default homepage

javascripts/discourse/components/dc-categories-nav.js.es6, javascripts/discourse/connectors/below-site-header/categories-nav.js.es6, javascripts/discourse/templates/components/dc-categories-nav.hbs, settings.yml
**What:**
Add support for admins to render custom links on the categories nav
**Why:**
https://app.asana.com/0/1168997577035609/1181476354560133
**How:**
Enhance `dc-categories-nav` component with a new computed property `customLinks` that gets populated by admins.
**Media:**
https://www.loom.com/share/2700643cf6b445cea74452968e976424
=> Categories custom links

scss/templates/components/list-controls.scss
**What:**
Enable categories list items to fill all available space in dropdown
**Why:**
Dropdown items should take the space available in the dropdown, this is the way it looks now
**How:**
The items were having a `max-width` of `345px`, that is the reason they were not filling all the space, by setting the max-width as 100% now the items look like this
=> fix(categories-dropdown): use all space available for categories items

javascripts/discourse/components/dc-categories-nav.js.es6
**What:**
Add checks to avoid empty values or unexpected formats
**Why:**
Issue after deploy https://github.com/debtcollective/discourse-debtcollective-theme/pull/68 with empty URL values makes community to crash
**How:**
Add checks before try to render or apply further parsing process of given format.
**Media:**
https://www.loom.com/share/d21270ad29794669acf1a0c2903cffdb
=> fix(categories-nav): validate unexpected formats before render

scss/connectors/categories-nav.scss
Asana ticket: https://app.asana.com/0/1168997577035609/1183039448302281/f
**What:**
Restore the dimension of the header navigation links
**Why:**
On a previous change, the header dimensions were changed and turned smaller
**How:**
By rolling back the dimensions as they were before
**Media**
Video: https://www.loom.com/share/11067f458179466289baceff8569b676
Before:
After:
=> fix(header-navigation): restore dimensions from header navigation links

javascripts/discourse/components/dc-topic-card-content.js.es6, javascripts/discourse/initializers/dc-header.js.es6, javascripts/discourse/templates/components/dc-topic-card-content.hbs, scss/button.scss, scss/templates/list/dc-topic-card.scss, scss/templates/user.scss
**What:**
Add fixes to allow notifications behaves similar to core theme
**Why:**
Users have issues to understand how to clear notifications
re https://app.asana.com/0/1168997577035609/1182066742206561
**How:**
> If you need more information go to the asana ticket where I also add couple videos showcasing the core behaviour and the previous wrong behaviour of the theme
=> Notifications improvements

package.json, scripts/update-theme.js, yarn.lock
**What:**
I created a script that will update the discourse theme in our CI, this could be either our development or production theme.
**Why:**
Every time that we added changes to discourse theme it was necessary to update the theme manually
https://app.asana.com/0/1168997577035609/1183011647269227
**How:**
By requesting discourse API to update the theme, we will integrate this script into our CI process, in this way, anytime we add a new change and merge either to development or production, the theme will have the latest changes.
Media: 
[Update a theme manually](https://www.loom.com/share/51f86e3935fe47108a99dddca62f48d2)
[Update a theme with the script](https://www.loom.com/share/b1bab9fe489648709598890ab26ec82b)
=> feat(discourse-theme): script to update discourse theme

.circleci/config.yml, scripts/update-theme.js
**What:**
Create circleCI configuration to run `update-theme` script when merging to develop
**Why:**
To enable: https://app.asana.com/0/1159164196409129/1183011647269227/f
**How:**
I created a job that will use a node docker image and run the `update-theme` script. Something to taking in count:
Notes:
We need to setup some env variables at circle ci context in order for the script to work
```bash
- DISCOURSE_THEME_ID
- DISCOURSE_APP_BASE_URL
- DISCOURSE_API_KEY
- DISCOURSE_API_USERNAME
```
=> Create circleCI configuration to run update-theme script when merging to develop

README.md, javascripts/discourse/components/categories-only.js.es6, javascripts/discourse/initializers/dc-popup.js.es6, javascripts/discourse/templates/components/dc-categories-only.hbs
**What:** Fix current efforts section, by pulling topics with the `current-efforts` tag instead of expecting Discourse to provide those topics on the first load.
**Why:** Currently, the **Current Efforts** section doesn't work as we expect, because Discourse has a specific behavior around `global_pinned` topics where not all the pinned topics are fetched on the first load. To fix this, we are creating a new tag only for staff to use called `current-efforts`. Now if we want to display a topic in the current-efforts section, is just a matter of tagging that topic.
Fixes https://app.asana.com/0/1168997577035609/1178339208108259
**How:**
- Request current efforts topics after load doing an ajax call to `tags/current-efforts.json` endpoint.
=> fix(current-efforts): pull using 'current-efforts' tag

.circleci/config.yml
**What:**
Update Circle CI configuration file to run the `update_theme` job when merging into development
**Why:**
To fix #77 
**How:**
By setting `development` as the correct branch to run the ci job
=> fix(circle-ci): set correct branch to trigger job

scss/templates/composer.scss
**What:**
Apply the same size and border style to all elements that belong to input controls.
**Why:**
To fix: https://app.asana.com/0/1159164196409156/1185931631318929/f
**How:**
- Apply the same style rules to location controls that were being applied to event controls.
- Apply the same size for all elements at the first level beneath `title-and-category` section.
Media:
**Before**
**After**
=> fix(composer-fields): make all items of the same size

scss/widgets/embedded-posts.scss
**What:**
Avoid rendering twice the original message
**Why:**
When replying to a message, the original message was being rendered twice on the message composer
**How:**
By adding a `display: none` to the content that was being duplicated
Media:
**Before:**
**After:**
=> fix(message-composer): avoid rendering twice original message

javascripts/discourse/templates/modal/create-account.hbs
**What:**
Restore username input on login so user can create an account
**Why:**
there has been changes on the core code for Discourse that need to be addressed to display form as
expected. The changes that has been done so far can be found at https://github.com/discourse/discourse/commits/master/app/assets/javascripts/discourse/app/templates/modal/create-account.hbs
related to https://app.asana.com/0/1168997577035609/1187007774305284
[Breaking changes reference](https://user-images.githubusercontent.com/1425162/89052084-782b3580-d355-11ea-91ea-974eb4676e38.png)
**How:**
Use the same logic than Discourse core to render the username field
**Media:**
=> fix(create-account): the logic behind username input was out dated

javascripts/discourse/templates/user/summary.hbs, scss/templates/user.scss, scss/variables.scss
**What:**
- Update styles on user summary to match the design
**Why:**
To address: https://app.asana.com/0/1159164196409129/1186341795801831/f subtask 4
**How:**
- Overwrite summary.hbs to customize the order of summary stats
- Overwrite default styles from discourse to use our own design
**Notes**
- Top categories and top badges were not included in the Figma design, so, I did remove them from the UI. If they need to be displayed let me know to add them.
Media:
https://www.loom.com/share/434732bf989a4218b7a2008840ff8239
=> feat(user-profile-summary): update styles to match design

scss/templates/user.scss
**What:**
Prevent scrolling on the navbar at user profile
**Why:**
To fix: #90 
**How:**
- Setting navbar overflow as hidden
=> fix(user-profile): prevent scrolling on profile nav

README.md, javascripts/discourse/widgets/dc-topic-title.js.es6
**What:**
Build category data only when `attrs.category` has value
**Why:**
To fix: https://app.asana.com/0/1159164196409156/1188957743196805/f
**How:**
- Add conditionals to compute the data
Notes:
- Remove duplicated section `testing` from README.md
=> fix(private-messages): build category only when attrs has category value

javascripts/discourse/initializers/dc-header.js.es6, scss/widgets/header.scss
**What:**
- Integrate the dc-dropdown component to display the `Take action` links
- Fix the header, hide menu items when the user is in a topic
**Why:**
Closes: https://www.loom.com/share/18ef071052574360b77c83b7495d2413
**How:**
- Load the script for the `@debtcollective/dc-header-component` package to use the `dc-dropdown`
- Avoid displaying the menu items when the user scrolls down inside a topic
https://www.loom.com/share/18ef071052574360b77c83b7495d2413
=> feat(header): integrate the dc-dropdown to display the take action links

javascripts/discourse/initializers/dc-home-logo.js.es6, javascripts/discourse/templates/components/dc-menu.hbs
**What:**
Make header logo route to the home page
**Why:**
Closes: https://app.asana.com/0/1168997577035609/1198498074643140/f
**How:**
Change the src attr for the logo links to redirect the user to the home page
https://www.loom.com/share/a3ae8c1cd72b4fa18078e193d3c1996d
=> Make header logo route to the home page

javascripts/discourse/initializers/dc-header.js.es6
**What:**
Avoid to load the header component to then only use the dropdown
**Why:**
We need to update to use packages with stencil version greater than 2.0 and also load only the dropdown instead the whole header component.
**How:**
Use `type="module"`scripts
**Media:**
=> build(header): use dropdown latest version instead

javascripts/discourse/initializers/dc-header.js.es6, scss/connectors/categories-nav.scss
**What:**
Reduce the size of the sub header navigation to keep visual hierarchy
**Why:**
The sub header nav should remain as links that we want to highlight but not as items we want to take precedence over 
everything in regards navigation. This suppose to be shortcuts for people that are somehow used to the community or
new comers that are exploring the page.
**How:**
Reduce size ~20%
**Extras:**
- Add `@latest` to pull always latest version of dc-dropdown-component
**Media:**
=> Aesthetics update over sub header nav

common/common.scss, javascripts/discourse/templates/navigation/category.hbs, scss/templates/components/list-controls.scss, scss/templates/navigation/category.scss
**What:**
Allow admins to add icon and backgrounds to a category without breaking the layout
**Why:**
Effort related to [Add category icon support](https://app.asana.com/0/1168997577035609/1198728038880465)
**How:**
- Replace the categories template to allow background customisation class
_(category template is not tight to any component so we are not able to do anything but replace or CSS styles)_
**Media:**
https://www.loom.com/share/5734d5688017485fb3fe4d06bbec5421
=> Category media support

scss/layout.scss, scss/templates/navigation/category.scss
**What:**
before:
after:
**Why:** Fix bug introduced in https://github.com/debtcollective/discourse-debtcollective-theme/commit/548a2bc8009ec703257b264139f4933d3647d057#diff-0c7610e42df35f47e6b223cb81e30220178b8d03cc6cd1dba2dfe9eb2d98a0efR44-R46
**How:**
- make background gradient `!important`
=> fix(background): add !important to background gradient

javascripts/discourse/components/categories-only.js.es6, javascripts/discourse/templates/components/categories-only.hbs, javascripts/discourse/templates/components/dc-categories-only.hbs, javascripts/discourse/templates/components/dc-category-card.hbs, javascripts/discourse/templates/mobile/components/categories-only.hbs, locales/en.yml
**What:**
- Remove `our collectives` section
- Rename `other categories` to `categories`
- Display a lock icon if a category is private
**Why:**
Closes: https://app.asana.com/0/1159164196409129/1199201056178941/f
**How:**
- Removing the code related to our collectives
- Renaming all the coincidences of `other categories` to be `categories`
- Modify the dc-category-card to display a lock icon if the category is `read_restricted`
https://www.loom.com/share/9b2a295db2754c72b648649f390dbe83
=> Remove our collectives and rename other categories

javascripts/discourse/initializers/dc-post.js.es6, scss/widgets/post.scss
**What:** enable topic-map in private messages
**Why:** fixes https://app.asana.com/0/1168997577035609/1182505564098417
**How:**
- enable topic-map component y post archetype is `private_message`
**Media:**
https://www.loom.com/share/932ac6fd09ba4c568cdebf63917f4bc2
**Notes:**
I'm not sure if we should enable this for topics too. Since we are making changes to usability, It may be a good idea to have the stats show on the first topic like the Discourse default theme.
=> feat: enable topic-map in private messages

javascripts/discourse/initializers/dc-email-login.js
**What:** redirect the user to after_signup_path when they log in via email
**Why:** Related to https://app.asana.com/0/1168997577035609/1199911153376989
**How:**
The backend now returns a value called `redirect_to` in the email login response. If this value is present we need to do the redirection. This functionality was added here https://github.com/debtcollective/discourse-debtcollective-sso/pull/16
=> redirect user to after_signup_path when they log in via email

javascripts/discourse/components/dc-topic-card-content.js.es6, javascripts/discourse/helpers/dc-format-date.js.es6, javascripts/discourse/templates/components/dc-category-card.hbs, javascripts/discourse/templates/components/dc-topic-card-content.hbs, javascripts/discourse/templates/components/dc-topic-engagement.hbs, javascripts/discourse/templates/components/topic-list.hbs, scss/button.scss, scss/card.scss, scss/templates/components/d-navigation.scss, scss/templates/components/list-controls.scss, scss/templates/components/topic-list.scss, scss/templates/list/dc-topic-card.scss, scss/variables.scss
**What:**
Update topic/category list screens to meet design expectations
**Why:**
relates to https://app.asana.com/0/1168997577035609/1199650841826375
**How:**
- Adjust cards in regards category and topic items
- Update large font to be ~18px
- Add better metadata to topic list items (created and replied dates)
- Update breadcrump icon colors
- Pinned icon for topic pinned
**Media:**
https://www.loom.com/share/fef9c3aea61a4be69cc1ecb459ce1f1d
=> Adjust topic list item

javascripts/discourse/initializers/dc-email-login.js, javascripts/discourse/initializers/dc-post.js.es6
**What:** fix: add missing DiscourseURL import
**Why:** Closes https://sentry.io/organizations/debtcollective/issues/2231709891
**How:**
- Add missing import
**Notes:**
Seems like Sentry now supports Discourse's source maps
=> fix: add missing DiscourseURL import

javascripts/discourse/components/dc-sidebar-subcategories.js.es6, javascripts/discourse/templates/components/dc-sidebar-link.hbs, javascripts/discourse/templates/navigation/category.hbs, scss/templates/components/dc-sidebar.scss
**What:**
Make sure subcategories are visible only once the parent gets clicked
**Why:**
Previously all parents expanded on click one item of the sidebar
https://app.asana.com/0/1168997577035609/1199957006065245
**How:**
Adjust condition to expand to remove unnecessary rule
**Extras:**
Minor aesthetics fixes for Safari sidebar items when excerpt is active, besides, add some small top margin for category titles when they don't have any background image.
**Media:**
https://www.loom.com/share/45cbda5b90d34643829abcb8340d7304
=> Sidebar and subcategories issue

javascripts/discourse/components/dc-sidebar.js.es6, javascripts/discourse/initializers/dc-homepage.js.es6, javascripts/discourse/templates/components/d-navigation.hbs, javascripts/discourse/templates/components/dc-sidebar.hbs, javascripts/discourse/templates/discovery.hbs, javascripts/discourse/templates/navigation/default.hbs, mobile/mobile.scss, scss/templates/components/d-navigation.scss, settings.yml
**What:**
- Add "All discussions" and "All events" links to sidebar
- Remove "All categories" link
**Why:**
closes https://app.asana.com/0/1168997577035609/1199979488935304
**How:**
- Set default homepage to `/latest` as list of categories is now deprecated
- Add needed markup for links
- Allow through settings to have admin to set the "events url"
- Use `/calendar` as events url by default as `upcoming-events` is not found in production
- Update sidebar to have information about the route current url injecting router.currentURL
**Media:**
https://www.loom.com/share/480d9a01b93c4f8da11745583bc4ba23
_Worth to mention that mobile devices don't have a quick link to events, currently, the sidebar displays only for desktop and mobile devices relies on the category breadcrumb to navigate_
=> Sidebar links

scss/layout.scss, scss/variables.scss
**What:**
Position content below header and categories
**Why:**
closes: https://app.asana.com/0/1168997577035609/1200153835254134
**How:**
Add padding to the main content, this padding is the sum of the header and categories height
=> Position content below header and categories

javascripts/discourse/initializers/dc-header.js.es6, scss/widgets/header.scss
**What:**
Add the same links than homepage into community header
**Why:**
We need to keep the spaces as similar as possible
**How:**
Follow approach similar to https://github.com/debtcollective/home/pull/100
**Media:**
https://www.loom.com/share/9ef4938c429e4ba0b9e5cce8e7b31d32
**Notes:**
_Once we define a design approach for this we should think on allow admin to add the links_
=> Unify header links with other spaces

javascripts/discourse/initializers/dc-homepage.js.es6
**What:**
Prevent wrong usage over `setDefaultHomepage` method
**Why:**
https://sentry.io/organizations/debtcollective/issues/2372036190/?project=1393689
**How:**
following `app/assets/javascripts/discourse/tests/unit/lib/utilities-test.js` it seems this method
doesn't expect the `/` and that might be related to the error at
https://sentry.io/organizations/debtcollective/issues/2372036190/?project=1393689
Check [reference code here](https://github.com/discourse/discourse/blob/dc6b547ed89f652b5406489d76140b76cf8e0d1d/app/assets/javascripts/discourse/tests/unit/lib/utilities-test.js#L159)
**Notes:**
I couldn't reproduce the issue but chances are that this doesn't prevent user from use the app and fallback to the setting default of the homepage.
=> remove "/" from setDefaultHomepage input

javascripts/discourse/components/categories-only.js.es6, javascripts/discourse/components/dc-categories-only.js.es6, javascripts/discourse/components/dc-sidebar.js.es6, javascripts/discourse/templates/components/categories-only.hbs, javascripts/discourse/templates/components/dc-categories-only.hbs, javascripts/discourse/templates/components/dc-sidebar.hbs, locales/en.yml
**What:**
Allow users to trigger the category creation/edition properly
**Why:**
https://app.asana.com/0/1168997577035609/1200291816614955
**How:**
Use the router in order to transition to the page that handles this.
Emulate https://github.com/discourse/discourse/blob/f56a22bd2e0c98ea43a970574b7651aeb71ddd74/app/assets/javascripts/discourse/app/routes/discovery-categories.js#L107
**Media:**
https://www.loom.com/share/6bf4d6ff53a5457a90d5d8439c3fc6a5
=> Fix category creation flow

common/after_header.html, common/head_tag.html, javascripts/discourse/initializers/dc-header.js.es6, scss/widgets/header.scss
**What:**
Add new header from https://github.com/debtcollective/packages/tree/development/packages/header-component
**Why:**
We want to unify the header across all the spaces within the organization
**How:**
- Visibility hidden over the built-in custom one _(we may want to delete the code if this prove to be useful and enough as it is right now)_
- Inject custom web component script using `head_tag.html`
- Add the new header using discourse slots `after_header.html`
**Media:**
_Waiting for ready to merge to upload latest_
https://www.loom.com/share/eb84a2691d3d4a14be0f99c6aab405f5
**Notes:**
- As we are not supporting env variables yet the session fetch won't work on testing environments
=> Add dc-header-component instead discourse built-in

.vscode/launch.json, javascripts/discourse/templates/components/dc-sidebar.hbs, scss/templates/components/dc-sidebar.scss
**What:**
Allow to community users to search after new header integration
**Why:**
After the new header integration we don't have a way to allow users to search for content
**How:**
Create a link on the sidebar in order to allow to use the advance search
> _Ideally, we wanted to move the search dropdown into a different area but the search build by discourse has been built with "Widgets" which is a custom concept from Discourse that doesn't play nice with the whole Ember ecosystem and make harder to do any customisation_
**Media:**
https://www.loom.com/share/a1cdf3ea14f745818702e129f2eaa75a
=> Add an option for users to search content

common/common.scss, javascripts/discourse/initializers/dc-header.js.es6
**What:**
Makes "Extra Black" weight available for Libre Franklin font.
**Why:**
The nav should render consistently across properties.
**How:**
Change to font import. 
Adding a 900 weight.
=> Adds 900 font weight to libre franklin
